EXECUTE create_job 'Sr. HVAC Engineer', '';
EXECUTE create_job 'Jr. HVAC Engineer', '';
EXECUTE create_job 'Facilities Engineer', '';
EXECUTE create_job 'Exhaust Engineer', '';
EXECUTE create_job 'Sr. Chemical Engineer', '';
EXECUTE create_job 'Jr. Chemical Engineer', '';
EXECUTE create_job 'Mechanical Engineer', '';
EXECUTE create_job 'Sr. Mechanic', '';
EXECUTE create_job 'Jr. Mechanic', '';
EXECUTE create_job 'Software Engineer', '';
EXECUTE create_job 'Wastewater Engineer', '';
EXECUTE create_job 'Plumber', '';
EXECUTE create_job 'Construction Worker', '';
EXECUTE create_job 'Instrumentation Engineer', '';
EXECUTE create_job 'Calibration Specialist', '';
EXECUTE create_job 'Construction Manager', '';
EXECUTE create_job 'Architectural Engineer', '';
EXECUTE create_job 'Automotive Engineer', '';
EXECUTE create_job 'Janitor', '';
EXECUTE create_job 'Truck Driver', '';
